# Default values for Mosquitto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Mosquitto configuration
##
mosquitto:
  ## Override the components name (defaults to `mosquitto`).
  ##
  nameOverride:

  ## Common configuration for all components
  ##
  common:
    ## Labels to be added to all components.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    ##
    labels: {}

    ## Annotations to be added to all components.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
    ##
    annotations: {}

  ## For Kubernetes RBAC support:
  ##
  rbac:
    ## Enable the creation of RBAC resources.
    ##
    create: true

  ## Role configuration.
  ##
  role:
    ## Labels to be added to the role.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    ##
    labels: {}

    ## Annotations for the role.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
    ##
    annotations: {}

  ## Role binding configuration.
  ##
  roleBinding:
    ## Labels to be added to the role binding.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    ##
    labels: {}

    ## Annotations for the role binding.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
    ##
    annotations: {}

  ## Service account configuration.
  ##
  serviceAccount:
    ## The name of the service account to use for api pods if rbac.create is false
    ##
    existing: default

    ## Labels to be added to the service account.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    ##
    labels: {}

    ## Annotations for the service account.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
    ##
    annotations: {}

  ## Secret definition
  ##
  secret:
    ## Labels to be added to the secret.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    ##
    labels: {}

    ## Annotations for the secret.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
    ##
    annotations: {}

  ## Mosquitto config file contents
  ##
  configFile:

  ## Mosquitto authentication settings
  ##
  authentication:
    ## Mosquitto password file contents
    ## To use authentication with mosquitto, you can set a list of password entries to be used.
    ## reference https://mosquitto.org/man/mosquitto_passwd-1.html to generate these entries.
    ##
    ## Example:
    ##   passwordEntries: |-
    ##     user1:$6$BKzw0RKerxV4Esbj$Uz5slWGB1TiOtYIEokEl0eR1YSEQAdKpcdRYMsLYbwjktlVzdLyGk41YCPGyMLnBePtdwPhkcm8kjGI0R9s57w==
    ##
    passwordFile:

    ## Location of password file
    ##
    passwordFilePath: /etc/mosquitto/password-file

  ## Mosquitto authorization settings
  ##
  authorization:
    ## Mosquitto ACL file contents
    ## To use authorizations with mosquitto, you can set a list of per user or pattern-based rules.
    ## reference https://mosquitto.org/man/mosquitto-conf-5.html for further information.
    ##
    ## Example:
    ##   aclFile: |-
    ##     pattern read cmnd/%u/#
    ##     pattern write stat/%u/#
    ##     pattern write tele/%u/#
    ##
    aclFile:

    ## Location of ACL file
    ##
    aclFilePath: /etc/mosquitto/acl-file

  ## Deployment configuration
  ##
  deployment:
    ## Number of replicas.
    ##
    replicas: 1

    ## Labels to be added to the deployment.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    ##
    labels: {}

    ## Annotations for the deployment.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
    ##
    annotations: {}

    ## Strategy for deployment updates.
    ##
    ## Example:
    ##
    ##   strategy:
    ##     type: RollingUpdate
    ##     rollingUpdate:
    ##       maxSurge: 1
    ##       maxUnavailable: 25%
    strategy: {}

  ## Pod(s) configuration
  ##
  pod:
    ## Labels to be added to the pod(s).
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    ##
    labels: {}

    ## Annotations for the pod(s).
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
    ##
    annotations: {}

    ## Node selector for pod(s).
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    ##
    nodeSelector: {}

    ## Tolerations for the pod(s).
    ##
    ## Example:
    ##   - key: "toleration=key"
    ##     operator: "Equal"
    ##     value: "value"
    ##     effect: "NoSchedule"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
    ##
    tolerations: {}

    ## Array of imagePullSecrets to allow pulling the Identity Set Management image from private registries.
    ## ps.: secrets must be manually created in the namespace.
    ## Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    ## Example:
    ##
    ##   imagePullSecrets:
    ##    - myRegistryKeySecretName
    ##
    imagePullSecrets:

    ## Affinities to add to the pod(s).
    ##
    ## Example:
    ##   nodeAffinity:
    ##     preferredDuringSchedulingIgnoredDuringExecution:
    ##       - weight: 50
    ##         preference:
    ##           matchExpressions:
    ##             - key: spot
    ##               operator: NotIn
    ##               values:
    ##                 - "true"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
    ##
    affinities: {}

    ## Configure volumes for the pod(s).
    ##
    ## Example:
    ##
    ##   - name: some-volume
    ##     configMap:
    ##       name: some-config
    ##
    ## Ref: https://kubernetes.io/docs/concepts/storage/volumes/
    ##
    volumes: {}

  ## Pod distribution budget configuration for pod(s)
  ##
  podDisruptionBudget:
    ## Labels to be added to the pod disruption budget.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    ##
    labels: {}

    ## Annotations for the pod disruption budget.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
    ##
    annotations: {}

    ## Minimum available pods. This can be either a number or percentage value
    ##
    minAvailable: 0

  ## Configmap settings.
  ##
  configMap:
    ## Labels to be added to the config map.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    ##
    labels: {}

    ## Annotations for the config map.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
    ##
    annotations: {}

  ## Persistent volume claim settings
  ##
  persistentVolumeClaim:
    ## Labels to be added to the persistent volume claim.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    ##
    labels: {}

    ## Annotations for the persistent volume claim.
    ##
    ## Example:
    ##   key1: "value1"
    ##   key2: "value2"
    ##
    ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
    ##
    annotations: {}

    ## Persistent volume claim access mode
    ##
    accessMode: ReadWriteOnce

    ## Persistent volume claim access mode
    ##
    size: 1Gi

  ## Mosquitto image to use in api server container(s).
  ##
  image: mosquitto

  ## Identity Set Management image tag.
  ##
  imageTag: 2.0.18-openssl

  ## Specific image digest to use in place of a tag.
  ## Ref: https://kubernetes.io/docs/concepts/configuration/overview/#container-images
  ##
  imageDigest:

  ## Specify a imagePullPolicy regarding the fetching of container images.
  ## Ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  imagePullPolicy: IfNotPresent

  ## Mosquitto container ports
  ##
  ports:
    ## MQTT port
    ##
    mqtt: 1883

    ## MQTTS port
    ##
    mqtts: 8883

    ## WebSocket port
    ##
    websocket: 9090

  ## Security context configuration for pod(s)
  ##
  securityContext:
    ## File System group ID
    ##
    fsGroup: 999